[package]
name = "skyguitar-scrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustube = "0.3.8"
tokio = { version = "1", features = ["full"] }